# Generated by Django 4.0.2 on 2022-02-15 20:14

from django.db import migrations, models
import django.db.models.deletion
import ichange40.fields
import ichange40.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ichange40.fields.UpperCaseCharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('placeholder', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('class_name', models.CharField(max_length=255, null=True, unique=True)),
                ('icon', models.FileField(upload_to='payments_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSystemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('attribute', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSystemCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('min', models.FloatField(help_text='Минимальная сумма обмена')),
                ('max', models.FloatField(help_text='Максимальная сумма обмена')),
                ('precision', models.PositiveIntegerField(help_text='Знаков после запятой')),
                ('requisite', models.CharField(blank=True, max_length=255, null=True)),
                ('commission', models.FloatField(default=0, help_text='Комиссия')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ichange40.currency')),
                ('from_inputs', models.ManyToManyField(blank=True, to='ichange40.Input')),
                ('from_notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ichange40.notice')),
                ('payment_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ichange40.paymentsystem')),
                ('to_inputs', models.ManyToManyField(blank=True, related_name='toinputs', to='ichange40.Input')),
                ('to_notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tonotice', to='ichange40.notice')),
            ],
            options={
                'unique_together': {('payment_system', 'currency')},
            },
        ),
        migrations.AddField(
            model_name='paymentsystem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ichange40.paymenttype'),
        ),
        migrations.AddField(
            model_name='input',
            name='rules',
            field=models.ManyToManyField(to='ichange40.Rule'),
        ),
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField(help_text='Сколько должны получить вы')),
                ('need_send', models.FloatField(help_text='Сколько получит юзер')),
                ('data', models.JSONField(blank=True, default={})),
                ('from_user_data', models.CharField(help_text='Информация от пользователя', max_length=255, null=True)),
                ('for_user', models.CharField(help_text='Для юзера', max_length=255, null=True)),
                ('code', models.CharField(default=ichange40.models.gen_code, max_length=30, unique=True)),
                ('status', models.PositiveIntegerField(choices=[[4, 'Не оплачена'], [7, 'Проверяем оплату'], [9, 'Новая'], [11, 'Оплачена']], default=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_payment_system_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ichange40.paymentsystemcurrency')),
                ('to_payment_system_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topaymentsystemcurrency', to='ichange40.paymentsystemcurrency')),
            ],
        ),
    ]
