# Generated by Django 4.0.2 on 2022-02-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ichange40', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_url', models.URLField()),
                ('inst_url', models.URLField()),
                ('tg_url', models.URLField()),
                ('support_url', models.URLField()),
                ('email_support', models.EmailField(max_length=254)),
                ('email_partner', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
